# Generated by Django 3.2.5 on 2021-07-28 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('courseCode', models.CharField(max_length=10)),
                ('courseName', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('courseSection', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('courseDesc', models.TextField(blank=True, default='', null=True)),
                ('courseRefNo', models.CharField(max_length=6)),
                ('courseStudent', models.ManyToManyField(blank=True, null=True, related_name='Disciples', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
