# Generated by Django 3.2.5 on 2021-07-28 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_alter_course_coursecreator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcemet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annTitle', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('annFile', models.FileField(blank=True, null=True, upload_to='files/')),
                ('annContent', models.TextField(blank=True, default='', null=True)),
                ('annTimestamp', models.DateTimeField(auto_now_add=True)),
                ('annCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnnouncementCreator', to=settings.AUTH_USER_MODEL)),
                ('annMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Announcements', to='home.course')),
            ],
        ),
    ]
