# Generated by Django 3.2.5 on 2021-07-28 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_announcemet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcemet',
            name='annCreator',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnnouncementCreator', to=settings.AUTH_USER_MODEL),
        ),
    ]
