# Generated by Django 3.2.5 on 2021-07-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_announcemet_anntitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='theme',
            field=models.CharField(default='', max_length=10),
        ),
    ]
